apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zerollm.fullname" . }}
  labels:
    {{- include "zerollm.labels" . | nindent 4 }}
data:
  zerollm.yaml: |
{{ .Values.config.contents | default "" | nindent 4 }}